title: "Chao's Research Workshop"
author: "Chao Huang"
description: "Here I will take some reading notes and note donw the problems I encountered in my research and the solutions to keep record of my research progress." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "tjhuangchao@mail.com"
twitter_username: "tjhuangchao"
github_username: "c-huang-tty"
linkedin_username: "Chao Huang"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

kramdown:
  input: kramdown
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    default_lang: cpp




defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
